-- =============================================================================
-- RAG-Anything Shared-State PostgreSQL Migration
-- Migration: 001_shared_state_tables
-- Target: PostgreSQL 16 (Docker Compose: postgres:16-alpine, container raganything-pg)
-- Description: Replace in-memory+JSON state stores with proper PG tables.
--
-- Background:
--   1. query_history: was in-memory list (max 100 entries) + query_history.json
--   2. conversations: was in-memory dict + conversations.json (whole-file rewrite)
--
-- Cross-DB note: user_id references SQLite auth.db users(id) INTEGER.
--   No FK possible across databases. Application-layer integrity enforced.
-- =============================================================================

BEGIN;

-- =============================================================================
-- 1. query_history — Immutable audit log of user queries to agents
-- =============================================================================
--
-- Access Patterns:
--   WRITE: 1 INSERT per query (very write-light)
--   READ:  SELECT ... [WHERE user_id = $1] ORDER BY time DESC LIMIT 50
--          Admin dashboard reads only. Filter by user_id is optional.
--
-- Row Estimates:
--   Current cap: 100 entries (agent.py trims to 100). If uncapped, ~1000/day
--   under heavy load. Average row: ~3 KB (answer text TOAST-ed, main tuple ~200 B).
--   100K rows = ~20 MB main data + ~300 MB TOAST. Negligible for PG.
--   Partitioning: NOT warranted. Even at 1M rows this is a small table.

CREATE TABLE IF NOT EXISTS query_history (
    -- Primary key: UUID v4 generated by the app (see agent.py: query_id)
    -- Using TEXT rather than UUID type so the app doesn't need uuid-to-string
    -- conversions and JSON persistence remains source-of-truth compatible.
    id          TEXT PRIMARY KEY,

    -- The user's natural-language query. NOT NULL because every record has one.
    query       TEXT NOT NULL,

    -- Query mode: 'text', 'vision', 'multimodal', 'hybrid'
    -- VARCHAR(20) is generous enough for any future modes.
    mode        VARCHAR(20) NOT NULL DEFAULT 'text',

    -- Agent execution mode: 'none', 'cot', 'react', etc.
    -- VARCHAR(50) covers all known agent modes + future expansion.
    agent_mode  VARCHAR(50) NOT NULL DEFAULT 'none',

    -- Full LLM response. TEXT (unlimited) because LLM answers can be very long
    -- (multi-paragraph with citations). Stored as TOAST (out-of-line) automatically
    -- by PG when exceeding ~2 KB.
    answer      TEXT NOT NULL DEFAULT '',

    -- Structured reasoning trace: {"steps": [...], "total_steps": N}
    -- JSONB for indexable/queryable structured data.
    -- Default '{}' rather than NULL so consumers never need null checks.
    reasoning_trace JSONB NOT NULL DEFAULT '{}',

    -- Image references produced or consumed during the query.
    -- JSONB array: ["url1", "url2", ...]
    images      JSONB NOT NULL DEFAULT '[]',

    -- When the query was recorded. TIMESTAMPTZ stores absolute UTC with zone info.
    -- This is the primary sort key for the dashboard.
    time        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Query latency in seconds. REAL (float4, 6 decimal digits) is sufficient
    -- for elapsed time; we don't need microsecond precision.
    elapsed     REAL NOT NULL DEFAULT 0,

    -- Knowledge base name used for this query.
    -- VARCHAR(255) matches typical KB name lengths.
    kb          VARCHAR(255) NOT NULL DEFAULT '',

    -- Agent identifier (UUID string, e.g. "a1b2c3d4")
    agent_id    VARCHAR(50) NOT NULL DEFAULT '',

    -- Conversation thread identifier (UUID string)
    thread_id   VARCHAR(50) NOT NULL DEFAULT '',

    -- User who made the query. INTEGER matches SQLite auth.db users(id).
    -- Cross-database reference — no FK possible. Application enforces integrity.
    -- NOT NULL because every query belongs to a user.
    user_id     INTEGER NOT NULL,

    -- Denormalized username for display efficiency.
    -- Saves a JOIN/auth.db round-trip on every dashboard render.
    -- VARCHAR(255) per RFC 3696 errata for email-as-username scenarios.
    username    VARCHAR(255) NOT NULL DEFAULT '',

    -- Whether the LLM fell back to a degraded mode (no KB context available).
    fallback    BOOLEAN NOT NULL DEFAULT FALSE
);

-- -------------------------------------------------------------------------
-- Index Strategy for query_history
-- -------------------------------------------------------------------------
-- Query 1 (user-filtered, 99% of non-admin reads):
--   SELECT * FROM query_history
--   WHERE user_id = $1 ORDER BY time DESC LIMIT 50;
-- Covered by: idx_query_history_user_time

-- Query 2 (admin: all users, no filter):
--   SELECT * FROM query_history ORDER BY time DESC LIMIT 50;
-- Covered by: idx_query_history_time

-- Query 3 (future: filter by agent_id):
--   SELECT * FROM query_history WHERE agent_id = $1 ORDER BY time DESC;
-- Partially covered by idx_query_history_time (can filter on agent_id with
-- index cond), but if agent-scoped queries become frequent, add:
--   CREATE INDEX idx_query_history_agent_time ON query_history(agent_id, time DESC);

-- Composite index for user-filtered queries (covers the WHERE + ORDER BY + LIMIT
-- pattern completely — index-only scan possible if SELECT list is narrow).
CREATE INDEX idx_query_history_user_time
    ON query_history(user_id, time DESC);

-- Standalone time index for admin "all users" queries.
-- Separate from the composite because a query without user_id filter
-- cannot use the leading column of idx_query_history_user_time efficiently.
CREATE INDEX idx_query_history_time
    ON query_history(time DESC);

-- Optional: if agent-scoped history views are added later, uncomment:
-- CREATE INDEX idx_query_history_agent_time
--     ON query_history(agent_id, time DESC);

-- -------------------------------------------------------------------------
-- Column Rationale Summary
-- -------------------------------------------------------------------------
-- | Column           | Type          | Why This Type                          |
-- |------------------|---------------|----------------------------------------|
-- | id               | TEXT PK       | App generates UUID strings, not UUID   |
-- | query            | TEXT NN       | NL queries vary widely in length       |
-- | mode             | VARCHAR(20)   | Bounded domain, CHECK not needed       |
-- | agent_mode       | VARCHAR(50)   | Bounded domain, room for new modes     |
-- | answer           | TEXT NN ''    | LLM output, can be 10K+ chars, TOASTed |
-- | reasoning_trace  | JSONB NN '{}' | Structured, never queried internally   |
-- | images           | JSONB NN '[]' | Array, never queried internally        |
-- | time             | TIMESTAMPTZ   | Absolute UTC, sort key                 |
-- | elapsed          | REAL          | Float seconds, 6-digit precision       |
-- | kb               | VARCHAR(255)  | KB name, no FK (managed elsewhere)     |
-- | agent_id         | VARCHAR(50)   | Agent UUID string                      |
-- | thread_id        | VARCHAR(50)   | Thread UUID string                     |
-- | user_id          | INTEGER NN    | SQLite auth.db reference               |
-- | username         | VARCHAR(255)  | Denormalized for display               |
-- | fallback         | BOOLEAN       | Degraded-mode indicator                |


-- =============================================================================
-- 2. conversations — User-scoped chat threads (ConversationManager replacement)
-- =============================================================================
--
-- Access Patterns:
--   list_threads:    SELECT ... WHERE user_id = $1 ORDER BY updated_at DESC
--   get_context:     SELECT messages WHERE thread_id = $1 ORDER BY created_at DESC LIMIT N
--   add_message:     INSERT INTO messages (thread_id, role, content)
--                    UPDATE conversations SET updated_at = NOW() WHERE id = $1
--   delete_thread:   DELETE FROM conversations WHERE id = $1 (CASCADE deletes messages)
--   get_or_create:   SELECT by id + INSERT on miss (or INSERT ... ON CONFLICT DO NOTHING)
--
-- Row Estimates:
--   Threads: bounded at 50 per user (application-enforced). At 1000 users = 50K max.
--   Messages: ~10-50 per active thread. At 50K threads * 20 avg = 1M messages.
--   Message tuple: ~300 B main + TOAST-ed content. 1M rows = ~300 MB + TOAST.
--   Partitioning: NOT warranted at these volumes.

CREATE TABLE IF NOT EXISTS conversations (
    -- Thread identifier. UUID-style string (12-char hex from the app).
    -- Same format as old code: f"th_{uuid.uuid4().hex[:12]}"
    id          VARCHAR(50) PRIMARY KEY,

    -- Owning user. INTEGER from SQLite auth.db users(id).
    -- Cross-database reference — no FK possible.
    -- NOT NULL: every thread belongs to exactly one user.
    user_id     INTEGER NOT NULL,

    -- Display title. Max 50 chars in old code (see conversation.py:148 title[:50]).
    -- We use 100 with a CHECK to allow longer titles if the UI evolves.
    title       VARCHAR(100) NOT NULL DEFAULT '新对话',

    -- Creation timestamp. Set once, never updated.
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Last activity timestamp. Updated on every add_message.
    -- This is the sort key for list_threads.
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Soft constraint: title fits within display limits.
    -- Hard delete is used (no deleted_at); if soft-delete needed later:
    --   ALTER TABLE conversations ADD COLUMN deleted_at TIMESTAMPTZ;
    CONSTRAINT chk_conversations_title_length CHECK (char_length(title) <= 100)
);

-- Index for listing threads by user, newest first.
-- This is the only read query on the conversations table itself.
-- Composite covers WHERE user_id = $1 + ORDER BY updated_at DESC.
CREATE INDEX idx_conversations_user_updated
    ON conversations(user_id, updated_at DESC);


-- =============================================================================
-- 3. messages — Individual messages within a conversation thread
-- =============================================================================
--
-- Normalized rather than JSONB because:
--   1. Messages have structural constraints (role CHECK, content length).
--   2. Append-only — no updates, no partial modifications.
--   3. The JOIN cost is trivial with the thread_id index.
--   4. Future: allows searching across messages if needed.
--   5. Cleaner: PG handles TOAST, ordering, and constraint enforcement;
--      the app doesn't need to validate a JSONB array on every read.

CREATE TABLE IF NOT EXISTS messages (
    -- Synthetic PK. BIGSERIAL gives us 2^63 IDs — effectively unlimited.
    -- We don't need a UUID per message; BIGSERIAL is faster and more compact.
    id          BIGSERIAL PRIMARY KEY,

    -- Parent thread. CASCADE DELETE: when a thread is deleted, all its
    -- messages are automatically removed. Matches old delete_thread behavior.
    thread_id   VARCHAR(50) NOT NULL
                REFERENCES conversations(id) ON DELETE CASCADE,

    -- Message role. Constrained to known values.
    -- 'system' included for future use (e.g., injected system notes).
    role        VARCHAR(10) NOT NULL,

    -- Message content. Max 10000 chars enforced at DB level.
    -- TEXT with a CHECK (not VARCHAR(10000)) because TEXT + CHECK gives
    -- the same constraint without the VARCHAR length overhead in catalogs.
    -- Also, PG stores TEXT and VARCHAR identically internally.
    content     TEXT NOT NULL,

    -- Message timestamp. Used for ordering within a thread.
    -- NOT NULL with DEFAULT NOW() — every message has a timestamp.
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Domain constraints
    CONSTRAINT chk_messages_role CHECK (role IN ('user', 'assistant', 'system')),
    CONSTRAINT chk_messages_content_length CHECK (char_length(content) <= 10000)
);

-- Index for fetching messages by thread, newest first.
-- This covers both:
--   get_context:         WHERE thread_id = $1 ORDER BY created_at DESC LIMIT N
--   get_context_for_rewrite: WHERE thread_id = $1 ORDER BY created_at DESC LIMIT 6
-- The composite index covers the FK lookup AND the ORDER BY.
CREATE INDEX idx_messages_thread_created
    ON messages(thread_id, created_at DESC);

-- -------------------------------------------------------------------------
-- Optional: Partial index for recent messages (if threads grow very long).
-- Uncomment if some threads exceed 1000 messages and you always query last 6-10.
--   CREATE INDEX idx_messages_thread_recent
--       ON messages(thread_id, created_at DESC)
--       WHERE created_at > NOW() - INTERVAL '90 days';
-- This keeps the index small by only indexing recent messages.
-- -------------------------------------------------------------------------

-- =============================================================================
-- 4. agent_conversations — Agent-scoped conversation threads (AgentManager)
-- =============================================================================
--
-- NOTE: This table is OPTIONAL. The task specifies only ConversationManager
-- and query_history. However, AgentManager (agent_manager.py) has its own
-- conversation storage (per agent_id, per-file JSON) that would also benefit
-- from PG migration. Uncomment if you want to migrate AgentManager concurrently.
--
-- Differences from conversations table:
--   - Scoped by agent_id in addition to user_id
--   - Uses owner_id (same semantics as user_id)
--   - Additional thread-level fields: kb_name, llm_model, system_prompt
--   - Messages stored on the thread (no separate messages table in old code)
--
-- If NOT migrated now, AgentManager continues using JSON files and this table
-- is left commented out as future reference.

-- CREATE TABLE IF NOT EXISTS agent_conversations (
--     id              VARCHAR(50) PRIMARY KEY,
--     agent_id        VARCHAR(50) NOT NULL,
--     owner_id        INTEGER NOT NULL,
--     title           VARCHAR(100) NOT NULL DEFAULT '新对话',
--     kb_name         VARCHAR(255) NOT NULL DEFAULT '',
--     llm_model       VARCHAR(100) NOT NULL DEFAULT '',
--     system_prompt   TEXT NOT NULL DEFAULT '',
--     created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     CONSTRAINT chk_agent_conv_title_length CHECK (char_length(title) <= 100)
-- );
--
-- CREATE INDEX idx_agent_conv_agent_updated
--     ON agent_conversations(agent_id, updated_at DESC);
--
-- CREATE INDEX idx_agent_conv_owner
--     ON agent_conversations(owner_id, updated_at DESC);
--
-- CREATE TABLE IF NOT EXISTS agent_messages (
--     id          BIGSERIAL PRIMARY KEY,
--     thread_id   VARCHAR(50) NOT NULL
--                 REFERENCES agent_conversations(id) ON DELETE CASCADE,
--     role        VARCHAR(10) NOT NULL,
--     content     TEXT NOT NULL,
--     created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--     CONSTRAINT chk_agent_msg_role CHECK (role IN ('user', 'assistant', 'system')),
--     CONSTRAINT chk_agent_msg_content CHECK (char_length(content) <= 10000)
-- );
--
-- CREATE INDEX idx_agent_msg_thread_created
--     ON agent_messages(thread_id, created_at DESC);


-- =============================================================================
-- 5. Utility: auto-update updated_at trigger (optional convenience)
-- =============================================================================
--
-- Keeps conversations.updated_at in sync without application code.
-- Alternative: update updated_at explicitly in the add_message transaction.
-- Using a trigger eliminates the risk of forgetting the UPDATE.

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger to conversations table.
-- Fires BEFORE UPDATE: any UPDATE to conversations auto-refreshes updated_at.
DROP TRIGGER IF EXISTS trg_conversations_updated_at ON conversations;
CREATE TRIGGER trg_conversations_updated_at
    BEFORE UPDATE ON conversations
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

COMMIT;

-- =============================================================================
-- Verification Queries (run after migration)
-- =============================================================================
-- \dt+                           — list all tables with sizes
-- \di+                           — list all indexes
-- \d+ query_history              — describe query_history table
-- \d+ conversations              — describe conversations table
-- \d+ messages                   — describe messages table
--
-- Test query patterns:
--   SELECT * FROM query_history WHERE user_id = 1 ORDER BY time DESC LIMIT 50;
--   EXPLAIN ANALYZE SELECT * FROM query_history ORDER BY time DESC LIMIT 50;
--   SELECT * FROM conversations WHERE user_id = 1 ORDER BY updated_at DESC;
--   SELECT * FROM messages WHERE thread_id = 'th_abc123' ORDER BY created_at DESC LIMIT 10;
--   EXPLAIN ANALYZE SELECT * FROM messages WHERE thread_id = 'th_abc123' ORDER BY created_at DESC LIMIT 6;
-- =============================================================================
